runtime: python
env: flex
service: default
runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "3.12"
entrypoint: gunicorn -b :$PORT rdc.wsgi

handlers:
- url: /static
  static_dir: staticfiles/
- url: /.*
  script: auto
  secure: always
